import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ToastProvider } from "@/components/providers/toaster-provider";
import { ConfettiProvider } from "@/components/providers/confetti-provider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ClientProviders } from '@/components/providers/client-providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ClientProviders>
          <ConfettiProvider />
          <ToastProvider />
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}

